/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:58d10bba-e824-4c0a-bafc-1af9c1d41356",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_17X5Pd5Q0",
    "aws_user_pools_web_client_id": "607395ub9s2fm649pms372kca8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dejbmehipbgz5la63aartfxdey.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-atej5s4kdzgw7lqiwvpc62jfte",
    "aws_user_files_s3_bucket": "amplifyappde9956cb81914fd7a16585bf32fe4ca421615-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
