/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:58d10bba-e824-4c0a-bafc-1af9c1d41356",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_17X5Pd5Q0",
  aws_user_pools_web_client_id: "607395ub9s2fm649pms372kca8",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://gvsw77m7hzdvth2tn5ehtvoqoq.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-d2xrqfcm5jfydowsvbszeqbq5q",
};

export default awsmobile;
